server:
    port: 8180
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/meet?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
