spring:
    application:
        name: auth-server

    profiles:
        active: dev

    # 日期类型转换成字符串返回
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        # 解决数据库有字段为null报错问题（相当于@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })配置）
        serialization:
            fail-on-empty-beans: false
