server:
    port: 8283
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/meet_order?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

    # 日期类型转换成字符串返回
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        # 解决数据库有字段为null报错问题（相当于@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })配置）
        serialization:
            fail-on-empty-beans: false


#mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    # 如果 mapper.xml 中的 resultType 没有指定实体类的包名，需要添加配置项
#    #type-aliases-package: com.dong.orderservice.web.entity
#
#    configuration:
#        # 开启驼峰命名映射
#        map-underscore-to-camel-case: true
#        # 将执行的SQL打印在控制台
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.dong.orderservice.web.entity

    configuration:
#        # 开启驼峰命名映射
#        map-underscore-to-camel-case: true
        # 将执行的SQL打印在控制台
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

