spring:
    application:
        name: billing-service

    profiles:
        active: dev

    # 日期类型转换成字符串返回
    jackson:
        date-format: yyyy-mm-dd HH:mm:ss
        time-zone: GMT+8

#        serialization:
#            fail-on-empty-beans: false
