server:
    port: 9181

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://120.24.189.253:3306/billing?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        hikari:
            auto-commit: true
            #空闲连接超时时长
            idle-timeout: 60000
            #连接超时时长
            connection-timeout: 60000
            #最大生命周期，0不过期
            max-lifetime: 500000
            #最小空闲连接数
            minimum-idle: 10
            #最大连接数量
            maximum-pool-size: 10

#    rabbitmq:
#        host: 120.24.189.253
#        port: 5672
#        username: admin
#        password: 123456
#        virtual-host: /

    # 日期类型转换成字符串返回
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        serialization:
            FAIL_ON_EMPTY_BEANS: false
