server:
    port: 9089

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://120.24.189.253:3306/my_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456

    rabbitmq:
        host: 120.24.189.253
        port: 5672
        username: admin
        password: 123456
        virtual-host: /

    # 日期类型转换成字符串返回
    jackson:
        date-format: yyyy-mm-dd HH:mm:ss
        time-zone: GMT+8

eureka:
    client:
        service-url:
            #单点模式
            defaultZone: http://192.168.154.127:9180/eureka/
            #高可用模式
#            defaultZone: http://peer1:8181/eureka/,http://peer2:8182/eureka/

ribbon:
    SocketTimeout: 300000
    ReadTimeout: 300000
    ConnectTimeout: 300000
