server:
    port: 8095

spring:
    application:
        name: product-service

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.154.127:3306/my_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456

    rabbitmq:
        addresses: 192.168.154.127:5672
        username: admin
        password: 123456
        virtual-host: /
        connection-timeout: 15000
eureka:
#    instance:
#        prefer-ip-address: true

    client:
        service-url:
            #单点模式
            defaultZone: http://localhost:8180/eureka/
            #高可用模式
#            defaultZone: http://peer1:8181/eureka/,http://peer2:8182/eureka/

