server:
    port: 8083
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.154.127:3306?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

    mvc:
        view:
            prefix: /
            suffix: .html
    thymeleaf:
        prefix: classpath:/static/
