server:
    port: 8083

spring:
    application:
        name: generator-server

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.154.127:3306/my_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456

    #配置页面存放路径
    thymeleaf:
        prefix: classpath:/static/

    mvc:
        view:
            prefix: /
            suffix: .html

