server:
    port: 8080
spring:
    application:
        name: demo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.168.154.127:3306/my_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        username: root
    profiles:
        include: sharding

    # 日期类型转换成字符串返回
    jackson:
        date-format: yyyy-mm-dd HH:mm:ss
        time-zone: GMT+8

        # 解决数据库有字段为null报错问题（相当于@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })配置）
        serialization:
            fail-on-empty-beans: false
