spring:
    shardingsphere:
        props:
            sql-show: true
        #            sql-simple: true
#        mode:
#            type: Standalone
#            repository:
#                type: File
#            overwrite: true
        datasource:
            ds:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://192.168.154.127:3306/my_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
                password: 123456
                type: com.zaxxer.hikari.HikariDataSource
                username: root
            names: ds
        rules:
            sharding:
                autotables:
                    billing_details:
                        actual-datasources: ds

                auto-tables:
                    billing_details:
                        sharding-strategy:
                            standard:
                                sharding-algorithm-name: database-interval
                                sharding-column: create_time
#                        key-generate-strategy:
#                            column: id
#                            key-generator-name: id-key
                sharding-algorithms:
                    database-interval:
                        props:
                            datetime-interval-amount: 1
                            datetime-interval-unit: MONTHS
                            datetime-lower: '2021-03-01 00:00:00'
                            datetime-pattern: yyyy-MM-dd HH:mm:ss
                            datetime-upper: '2022-10-01 00:00:00'
                            sharding-suffix-pattern: yyyyMM
                        type: INTERVAL


#                default-key-generate-strategy:
#                    column: id
#                    key-generator-name: id-key
#                key-generators:
#                    id-key:
#                        type: UUID


